document.writeln("<!DOCTYPE html PUBLIC \'-//W3C//DTD XHTML 1.0 Transitional//EN\'");
document.writeln("\'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\'>");
document.writeln("<html xmlns=\'http://www.w3.org/1999/xhtml\'>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' />");
document.writeln("<title></title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<style>");
document.writeln("#goTopBtn {position: fixed;line-height:44px;width:44px;bottom:35px;height:36px;cursor:pointer;display:none;");
document.writeln("background:url(img/Index/back_t.gif);}");
document.writeln("</style>");
document.writeln("	<div id=\'goTopBtn\'></div>");
document.writeln("	<script type=\'text/javascript\' src=\'js/jquery.min.js\'></script>");
document.writeln("	<script type=\'text/javascript\'>");
document.writeln("	 $(window).scroll(function(){");
document.writeln("	   var sc=$(window).scrollTop();");
document.writeln("	   var rwidth=$(window).width()");
document.writeln("	   if(sc>0){");
document.writeln("	    $(\'#goTopBtn\').css(\'display\',\'block\');");
document.writeln("	    $(\'#goTopBtn\').css(\'left\',(rwidth-55)+\'px\')");
document.writeln("	   }else{");
document.writeln("	   $(\'#goTopBtn\').css(\'display\',\'none\');");
document.writeln("	   }");
document.writeln("	 })");
document.writeln("	 $(\'#goTopBtn\').click(function(){");
document.writeln("	   var sc=$(window).scrollTop();");
document.writeln("	   $(\'body,html\').animate({scrollTop:0},500);");
document.writeln("	 })");
document.writeln("</script>");
document.writeln("</body>");
document.writeln("</html>");