document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-CN\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <title>派悦坊,非凡创意美味蛋糕</title>");
document.writeln("    <meta content=\'蛋糕,网上订购,生日,派对,红丝绒,纸杯蛋糕\' name=\'keywords\'>");
document.writeln("	<meta content=\'派悦坊,非凡创意美味蛋糕、经典纸杯蛋糕、大都会红丝绒蛋糕,均坚持选择纯进口原材料,给生日,派对带来不同惊喜，与朋友们、家人分享独一无二的美味快乐！\' name=\'description\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=Edge\'>");
document.writeln("");
document.writeln("    <!--<script src=\'js/less.js\'></script>-->");
document.writeln("    <!--<link rel=\'stylesheet\' href=\'less/index.less\'>-->");
document.writeln("    <script src=\'js/jquery.min.js\'></script>");
document.writeln("    <script src=\'js/bootstrap.min.js\'></script>");
document.writeln("    <!--字体图标链接-->");
document.writeln("    <link rel=\'stylesheet\' href=\'http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css\'>");
document.writeln("    <!--兼容(小于ie9加载js文件)-->");
document.writeln("    <!--[if lt IE 9]>");
document.writeln("    <!--<script src=\'https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\'></script>-->");
document.writeln("    <!--<script src=\'https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js\'></script>-->");
document.writeln("    <!--<![endif]&ndash;&gt;-->");
document.writeln("");
document.writeln("");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("        <!--轮播-->");
document.writeln("        <div class=\'row clearfix\'>");
document.writeln("            <div class=\'col-md-12 column\'>");
document.writeln("                <div class=\'carousel slide\' id=\'carousel-271592\'  data-interval=\'3000\' data-ride=\'carousel\'>");
document.writeln("                    <ol class=\'carousel-indicators\'>");
document.writeln("                        <li class=\'active\' data-slide-to=\'0\' data-target=\'#carousel-271592\'>");
document.writeln("                        </li>");
document.writeln("                        <li data-slide-to=\'1\' data-target=\'#carousel-271592\'>");
document.writeln("                        </li>");
document.writeln("                        <li data-slide-to=\'2\' data-target=\'#carousel-271592\'>");
document.writeln("                        </li>");
document.writeln("                        <li data-slide-to=\'3\' data-target=\'#carousel-271592\'>");
document.writeln("                        </li>");
document.writeln("                        <li data-slide-to=\'4\' data-target=\'#carousel-271592\'>");
document.writeln("                        </li>                        ");
document.writeln("                    </ol>");
document.writeln("                    <div class=\'carousel-inner\'>");
document.writeln("                        <div class=\'item active\'>");
document.writeln("                            <img alt=\'\' src=\'img/Index/banner_1.jpg\' />");
document.writeln("                        </div>");
document.writeln("                        <div class=\'item\'>");
document.writeln("                            <img alt=\'\' src=\'img/Index/banner_2.jpg\' />");
document.writeln("                        </div>");
document.writeln("                        <div class=\'item\'>");
document.writeln("                            <img alt=\'\' src=\'img/Index/banner_3.jpg\' />");
document.writeln("                        </div>");
document.writeln("                        <div class=\'item\'>");
document.writeln("                            <img alt=\'\' src=\'img/Index/banner_4.jpg\' />");
document.writeln("                        </div>");
document.writeln("                        <div class=\'item\'>");
document.writeln("                            <img alt=\'\' src=\'img/Index/banner_5.jpg\' />");
document.writeln("                        </div>                        ");
document.writeln("                    </div>");
document.writeln("                    <a class=\'left carousel-control\' href=\'#carousel-271592\' data-slide=\'prev\'><span class=\'glyphicon glyphicon-chevron-left\'></span></a>");
document.writeln("                    <a class=\'right carousel-control\' href=\'#carousel-271592\' data-slide=\'next\'><span class=\'glyphicon glyphicon-chevron-right\'></span></a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("</body>");
document.writeln("</html>");