document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-cn\'>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\' />");
document.writeln("		<meta http-equiv=\'X-UA-Compatible\' content=\'IE=9; IE=8; IE=EDGE\' />");
document.writeln("        <meta name=\'viewport\' content=\'user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1\'>");
document.writeln("     	<script src=\'js/jquery.min.js\'></script>");
document.writeln("        <script src=\'js/bootstrap.min.js\'></script>");
document.writeln("        <link rel=\'stylesheet\' href=\'css/bootstrap.min.css\' />");
document.writeln("        <link rel=\'stylesheet\' href=\'css/header.css\' />");
document.writeln("        <link rel=\'stylesheet\' href=\'css/common.css\' />");
document.writeln("        <link rel=\'stylesheet\' href=\'font_649150_vdbaicywran0cnmi/iconfont.css\' />");
document.writeln("        <script src=\'js/header.js\'></script>");
document.writeln("        <script src=\'js/header_jump.js\' type=\'text/javascript\' charset=\'utf-8\'></script>");
document.writeln("		<title>派悦坊-派悦-悦坊</title>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		");
document.writeln("		<div id=\'header\' class=\'navbar-fixed-top\'>");
document.writeln("			<div class=\'container-fluid header navbar navbar-inverse navbar-fixed-top\'>");
document.writeln("				<div class=\'down_list container-fluid\'>");
document.writeln("					<div class=\'row\'>");
document.writeln("						<h4 class=\'col-xs-12\'>当前城市:全国</h4>");
document.writeln("						<div class=\'col-xs-4\'>");
document.writeln("							<a href=\'javascript:void(0)\'>");
document.writeln("								<i class=\'iconfont col-xs-12 header_ico\'>&#xe615;</i>");
document.writeln("								<p class=\'col-xs-12 header_p\'>切换城市</p>");
document.writeln("							</a>");
document.writeln("						</div>");
document.writeln("						<div class=\'col-xs-4\'>");
document.writeln("							<a href=\'user.html\'>");
document.writeln("								<i class=\'iconfont col-xs-12 header_ico\'>&#xe60b;</i>");
document.writeln("								<p class=\'col-xs-12 header_p\'>个人中心</p>");
document.writeln("							</a>");
document.writeln("						</div>");
document.writeln("						<div class=\'col-xs-4\'>");
document.writeln("							<a href=\'products.html\'>");
document.writeln("								<i class=\'iconfont col-xs-12 header_ico\'>&#xe645;</i>");
document.writeln("								<p class=\'col-xs-12 header_p\'>产品搜索</p>");
document.writeln("							</a>");
document.writeln("						</div>");
document.writeln("						<div class=\'col-xs-4\'>");
document.writeln("							<a href=\'member.html\'>");
document.writeln("								<i class=\'iconfont col-xs-12 header_ico\'>&#xe613;</i>");
document.writeln("								<p class=\'col-xs-12 header_p\'>关于</p>");
document.writeln("							</a>");
document.writeln("						</div>");
document.writeln("						<div class=\'col-xs-4\'>");
document.writeln("							<a href=\'activity_1.html\'>");
document.writeln("								<i class=\'iconfont col-xs-12 header_ico\'>&#xe790;</i>");
document.writeln("								<p class=\'col-xs-12 header_p\'>活动</p>");
document.writeln("							</a>");
document.writeln("						</div>");
document.writeln("						<div class=\'col-xs-4\'>");
document.writeln("							<a href=\'dessert_table.html\'>");
document.writeln("								<i class=\'iconfont col-xs-12 header_ico\'>&#xe63b;</i>");
document.writeln("								<p class=\'col-xs-12 header_p\'>企业合作</p>");
document.writeln("							</a>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'container\'>");
document.writeln("			        <div class=\'row\'>");
document.writeln("			        	<div class=\'header_btn col-xs-2\'>");
document.writeln("							<a href=\'#\'>");
document.writeln("								<i class=\'iconfont\'>&#xe61e;</i>");
document.writeln("							</a>");
document.writeln("						</div>");
document.writeln("						<div class=\'header-logo col-lg-3 col-sm-3 col-md-3 col-xs-7\'>");
document.writeln("							<a href=\'index.html\'>");
document.writeln("								<img src=\'img/he-fo/logo.png\' class=\'img-responsive logo center-block\'/>");
document.writeln("							</a>");
document.writeln("						</div>");
document.writeln("						<div class=\'header-rgt-box col-xs-3\'>");
document.writeln("							<a href=\'#\' class=\'col-xs-4\'>En</a>");
document.writeln("							<a href=\'#\' class=\'col-xs-4\'>");
document.writeln("								<i class=\'iconfont\'>&#xe612;</i>");
document.writeln("							</a>");
document.writeln("							<a href=\'#\' class=\'col-xs-4\'>");
document.writeln("								<i class=\'iconfont\'>&#xe6f4;</i>");
document.writeln("							</a>");
document.writeln("						</div>");
document.writeln("						<ul class=\'nav navbar-nav col-lg-6 col-sm-6 col-md-6 ul-box\'>");
document.writeln("							<li>");
document.writeln("								<a href=\'javascript:void(0)\' class=\'ul-box-a\'>English</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'Store.html\' class=\'ul-box-a\'>门店</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'activity_1.html\' class=\'ul-box-a\'>活动</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'javascript:void(0)\' class=\'dropdown-toggle ul-box-a\' data-toggle=\'dropdown\'>");
document.writeln("									<i class=\'iconfont pppp_ico\'>&#xe612;</i>");
document.writeln("									<span class=\'pppp\'>全国</span>");
document.writeln("									<span class=\'caret\'></span>");
document.writeln("								</a>");
document.writeln("								<ul class=\'dropdown-menu mms\'>");
document.writeln("									<li>");
document.writeln("										<a href=\'javascript:void(0)\' class=\'where\'>北京</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'javascript:void(0)\' class=\'where\'>上海</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'javascript:void(0)\' class=\'where\'>深圳</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'javascript:void(0)\' class=\'where\'>成都</a>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'javascript:void(0)\' class=\'dropdown-toggle ul-box-a\' data-toggle=\'dropdown\'>");
document.writeln("									关于");
document.writeln("									<span class=\'caret\'></span>");
document.writeln("								</a>");
document.writeln("								<ul class=\'dropdown-menu\'>");
document.writeln("									<li>");
document.writeln("										<a href=\'member.html\'>会员</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'cake_coupon.html\'>蛋糕卡券</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'delivery_notice.html\'>配送须知</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'Activity_Pb.html\'>关于派悦坊</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'Activity_LovePb.html\'>爱上派悦坊</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'Activity_JoinPb.html\'>加入派悦坊</a>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'javascript:void(0)\' class=\'dropdown-toggle ul-box-a\' data-toggle=\'dropdown\'>");
document.writeln("									产品搜索");
document.writeln("									<span class=\'caret\'></span>");
document.writeln("								</a>");
document.writeln("								<ul class=\'dropdown-menu product_list\'>");
document.writeln("									<li>");
document.writeln("										<a href=\'#\'>太芒啦</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'#\'>生日蛋糕</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'#\'>星座蛋糕</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'#\'>纸杯蛋糕</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'#\'>意式冰激凌</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'#\'>礼盒</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'#\'>迷你方形垯</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'cake_coupon.html\'>蛋糕卡券</a>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'javascript:void(0)\' class=\'dropdown-toggle ul-box-a\' data-toggle=\'dropdown\'>");
document.writeln("									企业合作");
document.writeln("									<span class=\'caret\'></span>");
document.writeln("								</a>");
document.writeln("								<ul class=\'dropdown-menu\'>");
document.writeln("									<li>");
document.writeln("										<a href=\'dessert_table.html\'>甜品台</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'foretaste.html\'>企业试吃</a>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("						<ul class=\'nav navbar-nav navbar-right lo-re col-lg-2 col-sm-2 col-md-2 ul2-box\'>");
document.writeln("							<li class=\'show\'>");
document.writeln("								<a href=\'login.html\'>登录</a>");
document.writeln("							</li>");
document.writeln("							<li class=\'hide\'>");
document.writeln("								<a href=\'register.html\'>注册</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<div class=\'aaaa\' style=\'position: absolute; border: 1px solid white;\'></div>");
document.writeln("								<a href=\'shopping_car.html\'>");
document.writeln("									<i class=\'iconfont\'>&#xe600;</i>");
document.writeln("								</a>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("						<ul class=\'navbar-fixed-bottom ul3\'>");
document.writeln("							<li class=\'col-xs-4\'>");
document.writeln("								<a href=\'index.html\'>");
document.writeln("									<i class=\'iconfont\'>&#xe648;</i>");
document.writeln("								</a>");
document.writeln("							</li>");
document.writeln("							<li class=\'col-xs-4\'>");
document.writeln("								<a href=\'user.html\'>");
document.writeln("									<i class=\'iconfont\'>&#xe60a;</i>");
document.writeln("								</a>");
document.writeln("							</li>");
document.writeln("							<li class=\'col-xs-4\'>");
document.writeln("								<a href=\'shopping_car.html\'>");
document.writeln("									<i class=\'iconfont\'>&#xe600;</i>");
document.writeln("								</a>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</div>	");
document.writeln("				</div>");
document.writeln("			</div>	");
document.writeln("		</div>		");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");