document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-cn\'>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<meta http-equiv=\'X-UA-Compatible\' content=\'IE=9; IE=8; IE=EDGE\' />");
document.writeln("        <meta name=\'viewport\' content=\'user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1\'>");
document.writeln("        <script src=\'js/jquery.min.js\'></script>");
document.writeln("        <script src=\'js/bootstrap.min.js\'></script>");
document.writeln("        <link rel=\'stylesheet\' href=\'css/bootstrap.min.css\' />");
document.writeln("        <link rel=\'stylesheet\' href=\'css/common.css\' />");
document.writeln("        <link rel=\'stylesheet\' href=\'css/footer.css\' />");
document.writeln("        <link rel=\'stylesheet\' href=\'font_649150_vdbaicywran0cnmi/iconfont.css\' />");
document.writeln("        <script src=\'js/footer.js\'></script>");
document.writeln("		<title>派悦坊-派悦-悦坊</title>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		");
document.writeln("		<div class=\'container\' id=\'footer\'>");
document.writeln("			<div class=\'row\'>");
document.writeln("				<div class=\'col-lg-12 col-md-12 col-sm-12 col-xs-12 footer-box\'>");
document.writeln("					<div class=\'iphone col-xs-12\'>");
document.writeln("						<span class=\'iconfont ff\'>&#xe6f4;</span>");
document.writeln("						<span>");
document.writeln("							<a href=\'#\'>4008-3-14159</a>");
document.writeln("						</span>");
document.writeln("					</div>");
document.writeln("					<div class=\'address col-xs-12\'>");
document.writeln("						<span>Copyright 2010-2018 派悦坊，Ltd 京ICP备12046340</span>");
document.writeln("					</div>");
document.writeln("					<div class=\'col-lg-5 col-md-5 col-sm-5 col-xs-12 hidden-xs\' style=\'overflow: hidden;\'>");
document.writeln("						<div class=\'col-lg-12 col-md-12 col-sm-12 col-xs-4 pc-left\'>");
document.writeln("							<div class=\'info\'>");
document.writeln("								<span class=\'iconfont\'>&#xe6f4;</span>");
document.writeln("								<span>4008-3-14159</span>");
document.writeln("							</div>");
document.writeln("							<div class=\'info\'>");
document.writeln("								<span class=\'iconfont\'>&#xe617;</span>");
document.writeln("								<span>order@pantrysbest.com</span>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'col-lg-2 col-md-2 col-sm-2 hidden-xs pc-center\'>");
document.writeln("						<a href=\'#\' class=\'col-lg-6 col-md-6 col-sm-6\'>");
document.writeln("							<i class=\'iconfont\'>&#xe63d;</i>");
document.writeln("						</a>");
document.writeln("						<a href=\'#\' class=\'col-lg-6 col-md-6 col-sm-6\'>");
document.writeln("							<i class=\'iconfont\'>&#xe61f;</i>");
document.writeln("						</a>");
document.writeln("					</div>");
document.writeln("					<div class=\'col-lg-5 col-md-5 col-sm-5 hidden-xs pc-right\'>");
document.writeln("						<div class=\'col-lg-12 col-md-12 col-sm-12\'>");
document.writeln("							<img src=\'img/he-fo/footer-img.png\' class=\'img-responsive\'/>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'col-lg-12 col-md-12 col-sm-12 pc-addr hidden-xs\'>");
document.writeln("						<div class=\'info\'>北京市朝阳区神路街39号10幢3层4段92-93</div>");
document.writeln("						<div class=\'info\'>Copyright 2010-2018 派悦坊，Ltd 京ICP备12046340</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");